"""
Tracker v2 — Pipeline, Deadlines, Checklist, Win/Loss
Checklist now has:
- Status: Pending / In Progress / Done
- Responsible: Parthav / CA / Signatory / Notary / Bank
- Source type: App Generated / Upload Manual / External Party / Company Records
- Due date
- Section: Technical Bid / Financial Bid / Both
- Letterhead required: Yes/No
- Stamp paper: No / Rs.10 / Rs.100 / Rs.500
"""

import json, re, os
from pathlib import Path
from datetime import datetime, date, timedelta
from typing import Dict, List

RUNTIME_DIR = Path(os.environ.get("BIDNOBID_RUNTIME_DIR", "/tmp/bid-nobid"))
OUTPUT_DIR = RUNTIME_DIR / "data"
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)
DB_FILE = OUTPUT_DIR / "tenders_db.json"

PIPELINE_STAGES = [
    "Identified",
    "Analysed",
    "Pre-bid Sent",
    "Pre-bid Response Received",
    "Documents In Progress",
    "Documents Ready",
    "Submitted",
    "Under Evaluation",
    "Won",
    "Lost",
    "No-Bid",
    "Not Interested",
]

STAGE_COLORS = {
    "Identified": "#94A3B8",
    "Analysed": "#3B82F6",
    "Pre-bid Sent": "#8B5CF6",
    "Pre-bid Response Received": "#A78BFA",
    "Documents In Progress": "#F59E0B",
    "Documents Ready": "#EAB308",
    "Submitted": "#10B981",
    "Under Evaluation": "#06B6D4",
    "Won": "#059669",
    "Lost": "#EF4444",
    "No-Bid": "#6B7280",
    "Not Interested": "#9CA3AF",
}

# ── Responsible persons ───────────────────────────────────────
RESPONSIBLE_OPTIONS = [
    "Parthav Thakkar",   # Bid Executive — prepares documents
    "Hitesh Patel",      # Signatory — signs everything
    "CA / Auditor",      # Turnover certificate, balance sheets
    "Notary",            # Notarised declarations
    "SBI / Bank",        # EMD DD, FDR, solvency
    "HR Team",           # Employee declaration, EPF challan
    "Admin / Accounts",  # GST returns, PAN copies, registration certificates
    "Tech Team",         # Technical write-up, CV of resources
]

# Source type for each document
SOURCE_TYPES = {
    "app_generated": "Generated by App",
    "company_records": "Company Records — Ready",
    "ca_required": "CA / Auditor Required",
    "notary_required": "Notarisation Required",
    "bank_required": "Bank / SBI Required",
    "upload_manual": "Upload Manually",
    "external": "External Party",
}

# ── Standard documents for every tender ──────────────────────
# These are always in the checklist regardless of RFP
STANDARD_DOCS = [
    {
        "doc_key": "cover_letter",
        "doc": "Cover Letter / Bid Submission Letter",
        "category": "Bid Documents",
        "section": "Technical Bid",
        "source_type": "app_generated",
        "responsible": "Parthav Thakkar",
        "letterhead": True,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "Generated by app on Nascent letterhead. Hitesh Patel to sign.",
    },
    {
        "doc_key": "non_blacklisting",
        "doc": "Non-Blacklisting / Non-Debarment Self-Declaration",
        "category": "Legal Documents",
        "section": "Technical Bid",
        "source_type": "app_generated",
        "responsible": "Hitesh Patel",
        "letterhead": False,
        "stamp_paper": "Rs. 100",
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "Generated by app. Print on Rs.100 Non-Judicial Stamp Paper. Hitesh Patel to sign. Get Notarised.",
        "notary_required": True,
    },
    {
        "doc_key": "financial_standing",
        "doc": "Financial Standing Undertaking (Not under liquidation / bankruptcy)",
        "category": "Legal Documents",
        "section": "Technical Bid",
        "source_type": "app_generated",
        "responsible": "Hitesh Patel",
        "letterhead": True,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "Generated by app on letterhead. Hitesh Patel to sign.",
    },
    {
        "doc_key": "mii_declaration",
        "doc": "Make in India (MII) Declaration",
        "category": "Legal Documents",
        "section": "Technical Bid",
        "source_type": "app_generated",
        "responsible": "Hitesh Patel",
        "letterhead": True,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "Generated by app on letterhead.",
    },
    {
        "doc_key": "coi",
        "doc": "Certificate of Incorporation (COI) — Self-attested copy",
        "category": "Company Documents",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "Admin / Accounts",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "From company records. Self-attest each page.",
    },
    {
        "doc_key": "pan",
        "doc": "PAN Card — Self-attested copy",
        "category": "Company Documents",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "Admin / Accounts",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "PAN: AACCN3670J. Self-attest.",
    },
    {
        "doc_key": "gst",
        "doc": "GST Registration Certificate — Self-attested copy",
        "category": "Company Documents",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "Admin / Accounts",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "GSTIN: 24AACCN3670J1ZG. Self-attest.",
    },
    {
        "doc_key": "msme_udyam",
        "doc": "MSME Udyam Registration Certificate",
        "category": "Company Documents",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "Admin / Accounts",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": False,
        "note": "UDYAM-GJ-01-0007420. Download from udyamregistration.gov.in",
    },
    {
        "doc_key": "turnover_cert",
        "doc": "CA Certificate for Average Annual Turnover (last 3 FY)",
        "category": "Financial Documents",
        "section": "Technical Bid",
        "source_type": "ca_required",
        "responsible": "CA / Auditor",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "CA / Auditor",
        "note": "App provides format. CA to certify turnover for FY22-23, FY23-24, FY24-25. Include CA seal and membership number.",
    },
    {
        "doc_key": "balance_sheet_2223",
        "doc": "Audited Balance Sheet & P&L — FY 2022-23",
        "category": "Financial Documents",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "CA / Auditor",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": False,
        "note": "Certified copy from CA. All pages.",
    },
    {
        "doc_key": "balance_sheet_2324",
        "doc": "Audited Balance Sheet & P&L — FY 2023-24",
        "category": "Financial Documents",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "CA / Auditor",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": False,
        "note": "Certified copy from CA.",
    },
    {
        "doc_key": "balance_sheet_2425",
        "doc": "Audited Balance Sheet & P&L — FY 2024-25",
        "category": "Financial Documents",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "CA / Auditor",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": False,
        "note": "Certified copy from CA.",
    },
    {
        "doc_key": "cmmi_cert",
        "doc": "CMMI V2.0 Level 3 Certificate — Attested copy",
        "category": "Certifications",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "Admin / Accounts",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "Valid till 19-Dec-2026. Self-attest.",
    },
    {
        "doc_key": "iso_certs",
        "doc": "ISO Certificates (9001:2015, 27001:2022, 20000-1:2018) — Attested copies",
        "category": "Certifications",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "Admin / Accounts",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "All three certificates. Valid till Sep-2028. Self-attest each.",
    },
    {
        "doc_key": "employee_decl",
        "doc": "Employee Strength Declaration + EPF Combined Challan (latest month)",
        "category": "HR Documents",
        "section": "Technical Bid",
        "source_type": "app_generated",
        "responsible": "HR Team",
        "letterhead": True,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "App generates declaration format. HR to countersign. Attach latest EPF challan.",
    },
    {
        "doc_key": "experience_docs",
        "doc": "Experience Documents — Work Orders + Completion Certificates (qualifying projects)",
        "category": "Experience Documents",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "Parthav Thakkar",
        "letterhead": False,
        "stamp_paper": None,
        "needs_signature": True,
        "signatory": "Hitesh Patel",
        "note": "Select qualifying projects. Attach Work Order + Client Completion Certificate for each. Self-attest.",
    },
    {
        "doc_key": "poa_or_br",
        "doc": "Power of Attorney (POA) OR Board Resolution — Authorising Hitesh Patel",
        "category": "Legal Documents",
        "section": "Technical Bid",
        "source_type": "company_records",
        "responsible": "Hitesh Patel",
        "letterhead": False,
        "stamp_paper": "Rs. 100",
        "needs_signature": True,
        "signatory": "Director / Board",
        "note": "PoA on Rs.100 Stamp Paper OR Certified Board Resolution. Verify validity date.",
    },
]


def load_db() -> dict:
    if DB_FILE.exists():
        try:
            return json.loads(DB_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {"tenders": {}}


def save_db(db: dict):
    DB_FILE.write_text(json.dumps(db, indent=2, default=str), encoding="utf-8")


def days_left(deadline_str: str) -> int:
    if not deadline_str:
        return 999
    for fmt in ["%d-%m-%Y", "%d/%m/%Y", "%Y-%m-%d", "%d %b %Y"]:
        try:
            d = datetime.strptime(str(deadline_str).split()[0], fmt).date()
            return (d - date.today()).days
        except Exception:
            continue
    return 999


def get_deadline_alerts() -> List[Dict]:
    db = load_db()
    alerts = []
    for tid, t in db["tenders"].items():
        if t.get("verdict") not in ["BID", "CONDITIONAL"]:
            continue
        if t.get("status") in ["Submitted", "Won", "Lost", "No-Bid", "Not Interested"]:
            continue
        dl = days_left(t.get("deadline", ""))
        if 0 <= dl <= 7:
            alerts.append({
                "t247_id": tid,
                "brief": t.get("brief", "")[:80],
                "deadline": t.get("deadline", ""),
                "days_left": dl,
                "verdict": t.get("verdict", ""),
                "status": t.get("status", "Identified"),
                "checklist_pct": t.get("checklist_pct", 0),
                "prebid_sent": t.get("prebid_sent", False),
            })
    return sorted(alerts, key=lambda x: x["days_left"])


def get_pipeline_stats() -> Dict:
    db = load_db()
    stats = {s: 0 for s in PIPELINE_STAGES}
    for t in db["tenders"].values():
        s = t.get("status", "Identified")
        if s in stats:
            stats[s] += 1
    return stats


def get_win_loss_stats() -> Dict:
    db = load_db()
    won = lost = total_bid = 0
    won_value = lost_value = 0.0
    by_org = {}
    for t in db["tenders"].values():
        status = t.get("status", "")
        cost = float(t.get("estimated_cost_cr", 0) or 0)
        if status == "Won":
            won += 1; won_value += cost; total_bid += 1
        elif status == "Lost":
            lost += 1; lost_value += cost; total_bid += 1
        elif status == "Submitted":
            total_bid += 1
        org = t.get("org_name", "Unknown")[:40]
        if org not in by_org:
            by_org[org] = {"won": 0, "lost": 0, "submitted": 0}
        if status in ["Won", "Lost", "Submitted"]:
            key = status.lower() if status in ["Won", "Lost"] else "submitted"
            by_org[org][key] += 1
    win_rate = round((won / total_bid * 100) if total_bid > 0 else 0, 1)
    return {
        "won": won, "lost": lost, "total_bid": total_bid,
        "win_rate": win_rate,
        "won_value_cr": round(won_value, 2),
        "lost_value_cr": round(lost_value, 2),
        "by_org": dict(sorted(by_org.items(),
                              key=lambda x: x[1]["won"] + x[1]["lost"],
                              reverse=True)[:10]),
    }


def generate_doc_checklist(tender_data: Dict) -> List[Dict]:
    """
    Generate full document checklist for a tender.
    Combines:
    1. Standard Nascent docs (always needed)
    2. RFP-specific docs extracted from PQ criteria
    3. Stamp paper requirements from T&C
    4. EMD-specific item if EMD is required
    5. MSME EMD exemption if applicable
    """
    deadline_str = tender_data.get("bid_submission_date", "")
    tender_no = tender_data.get("tender_no", "")

    # Calculate due date = 2 days before bid submission
    due_date = ""
    for fmt in ["%d-%m-%Y", "%d/%m/%Y", "%d/%m/%Y %H:%M:%S", "%d-%m-%Y %H:%M:%S"]:
        try:
            d = datetime.strptime(deadline_str.split()[0], fmt).date()
            due_date = (d - timedelta(days=2)).strftime("%d-%m-%Y")
            break
        except Exception:
            continue

    checklist = []

    # ── 1. Standard docs (always present) ─────────────────────
    for i, doc in enumerate(STANDARD_DOCS):
        item = dict(doc)
        item.update({
            "id": f"std_{doc['doc_key']}",
            "sl_no": i + 1,
            "status": "Pending",
            "due_date": due_date,
            "done": False,
            "rfp_specific": False,
            "tender_no": tender_no,
        })
        checklist.append(item)

    # ── 2. EMD item ────────────────────────────────────────────
    emd = tender_data.get("emd", "")
    emd_exemption = tender_data.get("emd_exemption", "")
    if emd and emd not in ["—", "Not specified", ""]:
        # Check if MSME exemption available
        msme_exempt = any(k in str(emd_exemption).lower() for k in
                          ["msme", "mse", "exempt", "udyam"])
        if msme_exempt or "exempt" in str(emd_exemption).lower():
            checklist.append({
                "id": "emd_exemption_letter",
                "sl_no": len(checklist) + 1,
                "doc_key": "msme_emd_exemption",
                "doc": f"MSME EMD Exemption Letter (citing MSME Policy 2012) — EMD: {emd}",
                "category": "EMD",
                "section": "Technical Bid",
                "source_type": "app_generated",
                "responsible": "Parthav Thakkar",
                "letterhead": True,
                "stamp_paper": None,
                "needs_signature": True,
                "signatory": "Hitesh Patel",
                "status": "Pending",
                "due_date": due_date,
                "done": False,
                "rfp_specific": False,
                "note": f"App generates letter. Attach Udyam certificate. EMD amount: {emd}",
            })
        else:
            checklist.append({
                "id": "emd_dd",
                "sl_no": len(checklist) + 1,
                "doc_key": "emd_dd",
                "doc": f"EMD — Demand Draft / FDR — {emd}",
                "category": "EMD",
                "section": "Technical Bid",
                "source_type": "bank_required",
                "responsible": "Admin / Accounts",
                "letterhead": False,
                "stamp_paper": None,
                "needs_signature": False,
                "status": "Pending",
                "due_date": due_date,
                "done": False,
                "rfp_specific": False,
                "note": f"DD/FDR payable to beneficiary. Upload scanned copy. Deliver hard copy within 5 days. Amount: {emd}",
            })

    # ── 3. RFP-specific docs from PQ criteria ─────────────────
    pq = tender_data.get("pq_criteria", [])

    for item in pq:
        docs_text = item.get("details", "")
        clause = item.get("clause_ref", "")
        status_color = item.get("nascent_color", "GREEN")

        if not docs_text:
            continue

        # Split doc requirements by common delimiters
        docs = re.split(r'[|•\n,;]', docs_text)
        for doc in docs:
            doc = doc.strip()
            if len(doc) < 8:
                continue
            doc_lower = doc.lower()

            # Skip if already in standard docs
            if any(key in doc_lower for key in [
                "pan card", "gst", "incorporation", "cmmi", "iso", "msme", "udyam",
                "balance sheet", "turnover", "non-blacklist", "power of attorney",
                "board resolution", "epf", "employee strength", "cover letter",
                "make in india", "mii"
            ]):
                continue

            # Determine properties
            if any(k in doc_lower for k in ["stamp paper", "stamp duty", "notaris"]):
                stamp = "Rs. 100"
                source = "notary_required"
                responsible = "Hitesh Patel"
            elif any(k in doc_lower for k in ["work order", "completion", "performance cert", "client cert"]):
                source = "company_records"
                responsible = "Parthav Thakkar"
                stamp = None
            elif any(k in doc_lower for k in ["ca cert", "chartered accountant", "auditor cert"]):
                source = "ca_required"
                responsible = "CA / Auditor"
                stamp = None
            elif any(k in doc_lower for k in ["epf", "challan", "pf challan"]):
                source = "company_records"
                responsible = "HR Team"
                stamp = None
            elif any(k in doc_lower for k in ["cv", "resume", "curriculum vitae"]):
                source = "company_records"
                responsible = "HR Team"
                stamp = None
            elif any(k in doc_lower for k in ["form", "annexure", "declaration", "undertaking"]):
                source = "app_generated"
                responsible = "Parthav Thakkar"
                stamp = None
            else:
                source = "upload_manual"
                responsible = "Parthav Thakkar"
                stamp = None

            letterhead = source == "app_generated" or any(
                k in doc_lower for k in ["declaration", "undertaking", "letter", "certificate"]
            )

            checklist.append({
                "id": f"rfp_{clause}_{len(checklist)}",
                "sl_no": len(checklist) + 1,
                "doc_key": f"rfp_{re.sub(r'[^a-z0-9]', '_', doc_lower[:20])}",
                "doc": doc[:150],
                "category": "RFP Required",
                "section": "Technical Bid",
                "source_type": source,
                "responsible": responsible,
                "letterhead": letterhead,
                "stamp_paper": stamp,
                "needs_signature": True,
                "signatory": "Hitesh Patel",
                "status": "Pending",
                "due_date": due_date,
                "done": False,
                "rfp_specific": True,
                "clause_ref": clause,
                "urgency": "HIGH" if status_color in ["RED", "AMBER"] else "NORMAL",
                "note": f"Required as per {clause}. From: {SOURCE_TYPES.get(source, source)}",
            })

    # ── 4. Stamp papers summary from T&C ──────────────────────
    # Scan penalty/legal clauses for stamp paper mentions
    notes = tender_data.get("notes", [])
    for note in notes:
        note_lower = str(note).lower()
        if "stamp paper" in note_lower:
            import re as _re
            amounts = _re.findall(r'rs\.?\s*(\d+)', note_lower)
            for amount in amounts:
                checklist.append({
                    "id": f"stamp_{amount}_{len(checklist)}",
                    "sl_no": len(checklist) + 1,
                    "doc_key": f"stamp_rs{amount}",
                    "doc": f"Stamp Paper — Rs. {amount}",
                    "category": "Stamp Paper",
                    "section": "Technical Bid",
                    "source_type": "notary_required",
                    "responsible": "Admin / Accounts",
                    "letterhead": False,
                    "stamp_paper": f"Rs. {amount}",
                    "needs_signature": True,
                    "signatory": "Hitesh Patel",
                    "status": "Pending",
                    "due_date": due_date,
                    "done": False,
                    "rfp_specific": True,
                    "note": f"Mentioned in RFP notes. Procure Rs.{amount} Non-Judicial Stamp Paper.",
                })

    # Re-number
    for i, item in enumerate(checklist):
        item["sl_no"] = i + 1

    return checklist


def get_checklist_summary(checklist: List[Dict]) -> Dict:
    """Return summary stats for a checklist."""
    total = len(checklist)
    done = sum(1 for i in checklist if i.get("done"))
    in_progress = sum(1 for i in checklist if i.get("status") == "In Progress")
    pending = total - done - in_progress

    by_responsible = {}
    for item in checklist:
        r = item.get("responsible", "Unknown")
        if r not in by_responsible:
            by_responsible[r] = {"total": 0, "done": 0, "pending": 0}
        by_responsible[r]["total"] += 1
        if item.get("done"):
            by_responsible[r]["done"] += 1
        else:
            by_responsible[r]["pending"] += 1

    stamp_papers = [i for i in checklist if i.get("stamp_paper")]
    letterhead_docs = [i for i in checklist if i.get("letterhead")]
    external_items = [i for i in checklist if i.get("source_type") in
                      ["ca_required", "bank_required", "notary_required", "external"]]

    return {
        "total": total,
        "done": done,
        "in_progress": in_progress,
        "pending": pending,
        "completion_pct": round(done / total * 100) if total > 0 else 0,
        "by_responsible": by_responsible,
        "stamp_papers_needed": len(stamp_papers),
        "letterhead_docs_count": len(letterhead_docs),
        "external_items_count": len(external_items),
        "critical_pending": [i for i in checklist
                             if not i.get("done") and i.get("urgency") == "HIGH"],
    }
